name: Deploy to AWS App Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        id: build-image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO_NAME }}:$IMAGE_TAG .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO_NAME }}:$IMAGE_TAG
          echo "::set-output name=image::${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO_NAME }}:$IMAGE_TAG"

      - name: Deploy to App Runner
        id: deploy
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: my-app-runner-service
          image: ${{ steps.build-image.outputs.image }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: ${{ secrets.AWS_REGION }}
          cpu: 1
          memory: 2
          wait-for-service-stability-seconds: 600

      - name: Get service URL
        run: |
          echo "App Runner URL: ${{ steps.deploy.outputs.service-url }}"
